export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const INCREMENT_ASYNC_COUNTER = 'INCREMENT_ASYNC_COUNTER';
export const GET_PRINTERS = 'GET_PRINTERS';
export const GET_ASYNC_PRINTERS = 'GET_ASYNC_PRINTERS';
export const SELECT_PRINTERS = 'SELECT_PRINTERS';
export const PRINTER = 'PRINTER';
